version: '3.8'

services:
  # Service pour NGINX
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8008:80"
    volumes:
      - ./:/code
      # - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  # Service pour PHP-FPM (Application Laravel)
  app:
    image: php:8.1-fpm
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./:/code
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=portfolio
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  # Service pour la base de données MySQL
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: portfolio
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - dbdata:/var/lib/mysql

# Définition des volumes
volumes:
  dbdata:
